### ISSUE TITLE
Could not connect to lockdownd [latest libimobiledevice] [Ubuntu]

### ISSUE THREAD

**Issue by steverob** [google/ios-webkit-debug-proxy#260]
I built `libimobiledevice`, `usbmuxd` & `libplist` from source (`master`) and also used the `--disable-openssl` option when configuring `libimobiledevice`.

Still I get this following error -

```
~/dev/libimobiledevice master
❯ ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html
Listing devices on :9221
Could not connect to lockdownd. Exiting.: Operation now in progress
Unable to attach 995c0c8c7483d8f307ed5a98373d763102461f41 inspector
^C

~/dev/libimobiledevice master
❯ usbmuxd -V     
usbmuxd 1.1.1

~/dev/libimobiledevice master
❯ ios_webkit_debug_proxy -V                                 
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0
```

My system - `Linux 4.13.0-41-generic #46~16.04.1-Ubuntu`
OpenSSL Version - `1.0.2g`
iOS - `11.2.6` (iPhone X)

Also, `ideviceinfo -s` works great - 

```
BasebandCertId: 2232323234232
BasebandKeyHashInformation: 
 AKeyStatus: 2
 SKeyHash: somerandomsctring
 SKeyStatus: 0
BasebandSerialNumber: bOHOoQ==
BasebandVersion: 1.62.00
BoardId: 6
BuildVersion: 15D100
ChipID: 32789
DeviceClass: iPhone
DeviceColor: 1
DeviceName: Steve's iPhone
DieID: 11111111111111111
HardwareModel: D22AP
HasSiDP: true
PartitionType: GUID_partition_scheme
ProductName: iPhone OS
ProductType: iPhone10,3
ProductVersion: 11.2.6
ProductionSOC: true
ProtocolVersion: 2
TelephonyCapability: true
UniqueChipID: 11111111111111111
UniqueDeviceID: 1111111111111111111111111111
WiFiAddress: 34:08:bc:66:78:c2
```

Any help is appreciated. Thanks :)
